server:
  port: 9999
spring:
  application:
    name: customer-complaint-rest
  datasource:
    url: jdbc:mysql://localhost:3306/chiang_db?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=UTF8&useSSL=false
    username: root
    password: p@ssw0rd
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 1GB
      max-request-size: 1GB
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false

  mvc:
    throw-exception-if-no-handler-found: true

  jackson:
    time-zone: GMT+8

logging:
  level:
    java.sql.PreparedStatement: debug
  path: logs/
  file:
    max-size: 1GB

management:
  endpoints:
    web:
      exposure:
        include: '*'

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true


